### ISSUE TITLE
[Bug] Unable to run .mjs lambda

### ISSUE THREAD

**Issue by Lewenhaupt** [ServerlessLife/serverless-spy#16]
We use esm lambdas with .mjs extensions and I'm having trouble getting this to work.
The following is what we supply to esbuild: `--format=esm --out-extension:.js=.mjs --target='node18.13.0' --banner:js="import { createRequire } from 'module';const require = createRequire(import.meta.url);"`

Trying to run the lambda produces the following error:
```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /opt/nodejs/node_modules/interceptor.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'index'",
    "Require stack:",
    "- /opt/nodejs/node_modules/interceptor.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (/opt/nodejs/node_modules/interceptor.js:26727:13)",
    "    at load (/opt/nodejs/node_modules/interceptor.js:26744:19)",
    "    at getOriginalHandler (/opt/nodejs/node_modules/interceptor.js:26907:10)",
    "    at Runtime.handler (/opt/nodejs/node_modules/interceptor.js:26796:27)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
  ]
}
```

I've tried modifying the serverless-spy extension to output an .mjs version (using the same arguments we use) but this failed with the following error.
```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'interceptor'\nRequire stack:\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'interceptor'",
    "Require stack:",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
    "    at async start (file:///var/runtime/index.mjs:1282:23)",
    "    at async file:///var/runtime/index.mjs:1288:1"
  ]
}
```

I've also tried modifying `_tryRequire` in `UserFunction.ts` but I feel I'm at a bit of a loss as to what I should be doing here.

Any ideas or pointers as to what I should be doing?

**Comment by ServerlessLife** [comment]
Thank you for submitting the issue. I am currently on a trip, but I will look into the first thing on Monday. 

It would be really helpful if you have a sample project, so I can replicate the problem.

**Comment by Lewenhaupt** [comment]
Let me see if I can add a test to my branch. 😊

**Comment by Lewenhaupt** [comment]
I've managed to reproduce it and I found [this](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/main/src/UserFunction.js#L138) so I guess I can just update the UserFunction.ts to match that implementation and see if that works :)

**Comment by Lewenhaupt** [comment]
I think I got it working, they execute now at least so now on to writing my first test :)
In my cdk project I use yarn v3 and I encountered an issue with the styling of the web-ui because bootstrap and bootstrap-icons do not get placed inside the serverless-folder under node-modules but in the root of node-modules causing them to be missing.
