### ISSUE TITLE
CLI: --cdkstack not overriding chosen stack in UI

### ISSUE THREAD

**Issue by Lewenhaupt** [ServerlessLife/serverless-spy#19]
Using the --cdkstack option for the CLI does not work. I think what's happening is that the UI auto-selects the first stack in the dropdown which results in this block never being executed: 
```
if (!stack) {
   stack = options.cdkstack;
}
```
It also appears that then changing the stack in the dropdown never triggers a new attempt. I'm working around it by setting the --ws option right now and that works.
I think it would make sense to have --cdkstack affect the default selection of the dropdown instead of having it in the backend of the cli.
@ServerlessLife any thoughts?
Also, could you do a release with the latest changes? That way I can finally push my branch and let my co-workers start working with it. If it's not too much trouble :)

**Comment by Lewenhaupt** [comment]
> Hi Hugo,
> 
> I am releasing the new version right now. It takes quite some time for all the tests to run.
> 
> Let me know if you intend to fix those bugs, so we do not duplicate our work.
> 
> You can always reach me on: http://twitter.com/ServerlessL http://www.linkedin.com/in/marko-serverlesslife

Awesome! :)
Yeah, as long as you're ok with the approach I'll  see if I can fix it 👍

**Comment by ServerlessLife** [comment]
Hi @Lewenhaupt ,

I fixed the `--cdkstack` parameter in CLI in version 1.3.2

You also said in another issue:
> In my cdk project I use yarn v3 and I encountered an issue with the styling of the web-ui because bootstrap and bootstrap-icons do not get placed inside the serverless-folder under node_modules but in the root of node_modules causing them to be missing. Might be enough to just go up another level as a fallback.

I failed to reproduce that. Could you give me more details?

**Comment by Lewenhaupt** [comment]
Nice 😊

Yeah the issue I encounter is that bootstrap is not being installed in the node_modules dir under `project-root/node_modules/serverless-spy` but under `project-root/node_modules/bootstrap` which breaks the relative lookup and the web server.

**Comment by ServerlessLife** [comment]
@Lewenhaupt 
I am sorry. I am still unable to reproduce.

I already covered that scenario in the [code](https://github.com/ServerlessLife/serverless-spy/blob/8ec73300b7c69cdf1813be277269c2307ede6275/cli/cli.ts#L188), so the bootstrap can be anywhere and should still work.

**Comment by ServerlessLife** [comment]
Ha, ha. That is hilarious. You did fix it.

**Comment by Lewenhaupt** [comment]
Haha yeah! But very nice with the cdk stack fix 😊

**Comment by Lewenhaupt** [comment]
Haha yeah! But very nice with the cdk stack fix 😊
