### ISSUE TITLE
Does not spy on dynamodb.TableV2 Construct

### ISSUE THREAD

**Issue by m-radzikowski** [ServerlessLife/serverless-spy#28]
First of all - I'm just experimenting with the library, but it's great and will significantly simply my integration tests in the future. Great job!

CDK contains two Constructs for the DynamoDB table: `Table` and `TableV2`. `TableV2` is [improved and preferred Construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb-readme.html).

```ts
const table = new dynamodb.TableV2(this, 'Table', {
  partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },
});
```

But ServerlessSpy does not see this Construct and does not generate Spy Events for it.

**Comment by ServerlessLife** [comment]
Hi Maciej,

Thank you for reporting a missing feature.

I will add it shortly.

**Comment by ServerlessLife** [comment]
The missing feature is deployed.

If you have any other questions or suggestions, do not hesitate to contact me:
LinkedIn: http://www.linkedin.com/in/marko-serverlesslife
Twitter: https://twitter.com/ServerlessL

or, of course, create an issue.
