### ISSUE TITLE
bug: Attempts to add layers twice when using multiple S3 BucketDeployments

### ISSUE THREAD

**Issue by Lewenhaupt** [ServerlessLife/serverless-spy#32]
`Resource handler returned message: "Two different versions of the same layer are not allowed to be referenced in the same function. arn:aws:lambda:*:*:layer:Serve
rlessSpyPythonExtension*:18 and arn:aws:lambda:*:*:layer:ServerlessSpyPythonExtension*:18 are versions of the same layer. (Service: Lambda, Status C
ode: 400, Request ID: *)" (RequestToken: *, HandlerErrorCode: InvalidRequest)`

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html

This fails because BucketDeployment is backed by a singleton lambda which we will end up having twice in the list of nodes (or more). I think a simple fix (which would cover other scenarios like this) is to start checking in `internalSpyLambda` if it already has the SSPY_FUNCTION_NAME env var set and simply make an early return if it did.

I'll fix it later tonight.

**Comment by ServerlessLife** [comment]
@Lewenhaupt 
Thank you very much for doing that.

**Comment by Lewenhaupt** [comment]
@ServerlessLife No problem :) I'll see if I can add a test-case as well that should catch it if it appears again.
