### ISSUE TITLE
internalSpyEventBusRule throws Error for Rules that hasn't specified eventbus

### ISSUE THREAD

**Issue by JBaverlindInvoier** [ServerlessLife/serverless-spy#33]
internalSpyEventBusRule throws Error for Rules that hasn't specified eventbus.
Example: 

```
import * as events from "aws-cdk-lib/aws-events";

 new events.Rule(this, "exampleRule", {
     schedule: events.Schedule.cron({ minute: "0", hour: "8", day: "*", month: "*", year: "*" }),
 });
```

**Comment by Lewenhaupt** [comment]
Pretty sure the reason is because `EventBusName` is not required, and if omitted it would pick the default eventbus of the account. 
Maybe we could get away with just setting it to "default" if `eventBusName` is missing on the rule. We seem to only use it to construct the service key.
