### ISSUE TITLE
publishSpyEvent throws error for Dynamo "REMOVE" event

### ISSUE THREAD

**Issue by JBaverlindInvoier** [ServerlessLife/serverless-spy#41]
publishSpyEvent throws error for Dynamo "REMOVE" event due to unmarshall of undefined NewImage

**Comment by ServerlessLife** [comment]
Hi @JBaverlindInvoier,

Thank you for reporting the bug. I will deploy the fix shortly.

**Comment by ServerlessLife** [comment]
You can find the fix in version 2.2.3.

Thank you again.
